[package]
name = "ifc_rs_verify_derive"
version = "0.1.0-alpha-rc2"
edition = "2021"
license = "MIT"
description = "A proc-macro crate for the ifc crate"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.66"
quote = "1.0.36"
proc-macro2 = "1.0.85"
